
services:
  web:
    build: .
    image: andrew882024/event_master_backend:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  redis:
    image: redis:7
    ports:
      - "6379:6379"